name: ai_image
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - streamlit==1.31.1
    - requests==2.31.0
    - Pillow==10.2.0
    - python-dotenv==1.0.1
    - aiohttp==3.9.3
    - uvicorn>=0.15.0
    - cloudflare>=2.8.15
    # Dev dependencies
    - pytest>=6.0.0
    - black>=22.3.0
    - isort>=5.10.1
    - mypy>=0.982 